jobs:
  - job: Windows
    pool:
      vmImage: "windows-latest"
    steps:
      - script: |
          build-nupkg.bat
        displayName: "build-nupkg"
      - task: MSBuild@1
        displayName: "build TestProjects.VS2019"
        inputs:
          solution: "TestProjects/TestProjects.VS2019.sln"
          configuration: "Release"
          platform: "Any Cpu"
          restoreNugetPackages: "true"
  - job: Linux_NETCore2
    pool:
      vmImage: "ubuntu-latest"
    steps:
      - script: |
          build-nupkg.sh
        displayName: "build-nupkg"
      - task: MSBuild@1
        displayName: "build TestProjects.NETCore2"
        inputs:
          solution: "TestProjects/TestProjects.NETCore2.sln"
          configuration: "Release"
          platform: "Any Cpu"
          restoreNugetPackages: "true"
