jobs:
  - job: RelaxVersioner
    pool:
      vmImage: "windows-latest"
    steps:
      - script: |
          build-nupkg.bat
        displayName: "build-nupkg"
  - job: TestProjects_VS2019_Windows
    pool:
      vmImage: "windows-latest"
    steps:
      - script: |
          cd TestProjects; ../azure-pipelines/nuget.exe restore -ConfigFile ../azure-pipelines/NuGet.Config TestProjects/TestProjects.VS2019.sln
        displayName: "restore TestProjects.VS2019"
      - task: MSBuild@1
        displayName: "build TestProjects.VS2019"
        inputs:
          solution: "TestProjects/TestProjects.VS2019.sln"
          configuration: "Release"
          platform: "Any Cpu"
  - job: TestProjects_NETCore2_Windows
    pool:
      vmImage: "windows-latest"
    steps:
      - task: DotNetCoreCLI@1
        displayName: "build TestProjects.NETCore2"
        inputs:
          command: "build"
          projects: "TestProjects/TestProjects.NETCore2.sln"
          configuration: "Release"
          arguments: -p:Platform="Any CPU"
          feedsToUse: "config"
          nugetConfigPath: "azure-pipelines/NuGet.Config"
  - job: TestProjects_NETCore2_Linux
    pool:
      vmImage: "ubuntu-latest"
    steps:
      - task: DotNetCoreCLI@1
        displayName: "build TestProjects.NETCore2"
        inputs:
          command: "build"
          projects: "TestProjects/TestProjects.NETCore2.sln"
          configuration: "Release"
          arguments: -p:Platform="Any CPU"
          feedsToUse: "config"
          nugetConfigPath: "azure-pipelines/NuGet.Config"
  - job: TestProjects_Mono_Linux
    pool:
      vmImage: "ubuntu-latest"
    steps:
      - script: |
          cd TestProjects; mono ../azure-pipelines/nuget.exe restore -ConfigFile ../azure-pipelines/NuGet.Config TestProjects/TestProjects.VS2019.sln
        displayName: "restore TestProjects.Mono"
      - task: MSBuild@1
        displayName: "build TestProjects.Mono"
        inputs:
          solution: "TestProjects/TestProjects.Mono.sln"
          configuration: "Release"
          platform: "Any Cpu"
