jobs:
  - job: RelaxVersioner
    pool:
      vmImage: "windows-latest"
    steps:
      - script: |
          build-nupkg.bat
        displayName: "build-nupkg"
  - job: TestProjects_VS2019_Windows
    pool:
      vmImage: "windows-latest"
    steps:
      - task: NuGetCommand@2
        displayName: "restore TestProjects"
        inputs:
          restoreSolution: "TestProjects/TestProjects.sln"
          configuration: "Release"
          platform: "Any Cpu"
          feedsToUse: config
          nugetConfigPath: "azure-pipelines/NuGet.Config"
      - task: VSBuild@1
        displayName: "build TestProjects"
        inputs:
          solution: "TestProjects/TestProjects.sln"
          configuration: "Release"
          platform: "Any Cpu"
  - job: TestProjects_NETCore2_Windows
    pool:
      vmImage: "windows-latest"
    steps:
      - task: DotNetCoreCLI@1
        displayName: "build TestProjects.NETCore2"
        inputs:
          command: "build"
          projects: "TestProjects/TestProjects.NETCore2.sln"
          configuration: "Release"
          arguments: -p:Platform="Any CPU"
          feedsToUse: "config"
          nugetConfigPath: "azure-pipelines/NuGet.Config"
  - job: TestProjects_NETCore2_Linux
    pool:
      vmImage: "ubuntu-latest"
    steps:
      - task: DotNetCoreCLI@1
        displayName: "build TestProjects.NETCore2"
        inputs:
          command: "build"
          projects: "TestProjects/TestProjects.NETCore2.sln"
          configuration: "Release"
          arguments: -p:Platform="Any CPU"
          feedsToUse: "config"
          nugetConfigPath: "azure-pipelines/NuGet.Config"
  - job: TestProjects_Mono_Linux
    pool:
      vmImage: "ubuntu-latest"
    steps:
      - task: NuGetCommand@2
        displayName: "restore TestProjects.Mono"
        inputs:
          restoreSolution: "TestProjects/TestProjects.Mono.sln"
          configuration: "Release"
          platform: "Any Cpu"
          feedsToUse: config
          nugetConfigPath: "azure-pipelines/NuGet.Config"
      - task: MSBuild@1
        displayName: "build TestProjects.Mono"
        inputs:
          solution: "TestProjects/TestProjects.Mono.sln"
          configuration: "Release"
          platform: "Any Cpu"
