jobs:
  - job: RelaxVersioner
    pool:
      vmImage: "windows-latest"
    steps:
      - script: |
          build-nupkg.bat
        displayName: "build-nupkg"
  - job: TestProjects_VS2019_Windows
    pool:
      vmImage: "windows-latest"
    steps:
      - task: NuGetCommand@2
        displayName: "restore TestProjects.VS2019"
        inputs:
          command: "restore"
          workingDirectory: "TestProjects"
          restoreSolution: "TestProjects.VS2019.sln"
          configuration: "Release"
          feedsToUse: "config"
          nugetConfigPath: "NuGet.Config"
      - task: MSBuild@1
        displayName: "build TestProjects.VS2019"
        inputs:
          workingDirectory: "TestProjects"
          solution: "TestProjects.VS2019.sln"
          configuration: "Release"
          platform: "Any Cpu"
  - job: TestProjects_NETCore2_Windows
    pool:
      vmImage: "windows-latest"
    steps:
      - task: DotNetCoreCLI@1
        displayName: "build TestProjects.NETCore2"
        inputs:
          command: "build"
          workingDirectory: "TestProjects"
          projects: "TestProjects.NETCore2.sln"
          configuration: "Release"
          arguments: -p:Platform="Any CPU"
          feedsToUse: "config"
          nugetConfigPath: "NuGet.Config"
  - job: TestProjects_NETCore2_Linux
    pool:
      vmImage: "ubuntu-latest"
    steps:
      - task: DotNetCoreCLI@1
        displayName: "build TestProjects.NETCore2"
        inputs:
          command: "build"
          workingDirectory: "TestProjects"
          projects: "TestProjects.NETCore2.sln"
          configuration: "Release"
          arguments: -p:Platform="Any CPU"
          feedsToUse: "config"
          nugetConfigPath: "NuGet.Config"
  - job: TestProjects_Mono_Linux
    pool:
      vmImage: "ubuntu-latest"
    steps:
      - task: NuGetCommand@2
        displayName: "restore TestProjects.Mono"
        inputs:
          command: "restore"
          workingDirectory: "TestProjects"
          restoreSolution: "TestProjects.Mono.sln"
          configuration: "Release"
          feedsToUse: "config"
          nugetConfigPath: "NuGet.Config"
      - task: MSBuild@1
        displayName: "build TestProjects.Mono"
        inputs:
          workingDirectory: "TestProjects"
          solution: "TestProjects.Mono.sln"
          configuration: "Release"
          platform: "Any Cpu"
